name: TV-Canada Update Files

on:
  schedule:
   # - cron: '0 0,8,16 * * *'  # Runs at 00:00, 08:00, 16:00 UTC daily
   - cron: '1 0 * * *'  # Runs at 20:01 UTC (16:01 EDT) daily

  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-files:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz beautifulsoup4

      - name: Run TV-Mikhoul M3U collector script
        run: python BugsfreeMain/TV-Mikhoul.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add LiveTV/Mikhoul/LiveTV.m3u LiveTV/Mikhoul/LiveTV.txt LiveTV/Mikhoul/LiveTV.json LiveTV/Mikhoul/LiveTV
          git commit -m "TV-Mikhoul Update files - $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git pull --rebase origin main
          git push

  update-indexes:
    needs: update-files
    uses: bugsfreeweb/LiveTVCollector/.github/workflows/update-indexes.yml@main
    permissions:
      contents: write  # Required for the called workflow to push changes
